# Render Blueprint for BOM Platform
# This file describes the services that make up your application.

services:
  # The backend web service
  - type: web
    name: bom-platform-backend
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && python -c 'from models import init_db; init_db()' && uvicorn main:app --host 0.0.0.0 --port $PORT"
    # Port to listen on
    port: 8000
    # Add a persistent disk to store uploaded files and results
    disk:
      name: bom-platform-disk
      path: /var/data
    envVars:
      - key: GEMINI_API_KEY
        value: "YOUR_GEMINI_API_KEY_HERE"
      - key: DATABASE_URL
        fromDatabase:
          name: bom-platform-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.10.12

  # The frontend static site
  - type: static
    name: bom-platform-frontend
    env: node
    buildCommand: "cd frontend && npm install && npm run build"
    publishPath: "frontend/build"
databases:
  - name: bom-platform-db
    plan: free
